name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use go version 1.21.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          cache-dependency-path: src/go.sum
      
      - name: Run tests
        run: cd src && make test

  deploy:
    name: Deploy service on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Copy code to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "src,Dockerfile,docker-compose.yml"
          target: /home/${{ secrets.SSH_USERNAME }}/person-service

      - name: Run app on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/person-service
            docker compose up -d
        

  # build:
    # name: Autograding
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v3
    #     with:
    #       fetch-depth: 0

    #   # TODO build, test and deploy project

    #   - name: Run API Tests
    #     uses: matt-ball/newman-action@master
    #     with:
    #       collection: postman/[inst] Lab1.postman_collection.json
    #       environment: postman/[inst][heroku] Lab1.postman_environment.json
    #       delayRequest: 100
    #       reporters: '[ "cli" ]'

    #   - name: Autograding
    #     uses: education/autograding@v1
    #     continue-on-error: true

    #   - name: Github auto grader mark
    #     uses: Romanow/google-sheet-autograder-marker@v1.0
    #     with:
    #       google_token: ${{secrets.GOOGLE_API_KEY}}
    #       sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
    #       homework_number: 1
    #       user_column: 'D'
    #       column_offset: 'F'
    #       mark: "'+"
